# Generated by Django 5.0.2 on 2024-03-08 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='post_message',
        ),
    ]
