# Generated by Django 5.0.2 on 2024-03-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_listing_category_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='close_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_close_by_date',
            field=models.BooleanField(default=False),
        ),
    ]
