# Generated by Django 5.0.2 on 2024-03-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_close_date_listing_is_close_by_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='is_close_by_date',
        ),
        migrations.AlterField(
            model_name='listing',
            name='close_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
